include_recipe 'mirror::mirror_config'
include_recipe 'mirror::packages_update'
include_recipe 'mirror::packages_setup'
include_recipe 'mirror::packages_install'
include_recipe 'mirror::config_ssh'
include_recipe 'mirror::init_ssh'
